version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./staticfiles:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: infra_dev_frontal
    ports:
      - 8080:80